# Generated by Django 5.1.1 on 2024-09-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_brand_product_category_product_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='INDIA', max_length=100),
        ),
    ]
